---
abstract: 'Gtk2 frontend for perl watcher'
author:
  - 'Ivan Baidakou <dmol@gmx.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-PerlWatcher-UI-Gtk2
requires:
  App::PerlWatcher::Engine: 0.13
  Devel::Comments: v1.1.4
  File::ShareDir::ProjectDistDir: v0.4.4
  Gtk2: 1.247
  Gtk2::TrayIcon: 0.06
  aliased: 0.31
version: 0.05
